### ISSUE TITLE
Notification Icon Not Visible

### ISSUE THREAD

**Issue by sween64** [CreatureSurvive/consolidation#2]
App icon and notification icon not visible. Attached imagery shows the NC with full size but the bug occurs both on the LS and in the NC and with Medium, Large and Full Size. 
https://imgur.com/a/dlc5d

Tweaks installed:
https://pastebin.com/TSY1A3cx

**Comment by CreatureSurvive** [comment]
thanks for the report, sorry your having issues. this is something that is already fixed in alpha 5 which will hopefully be out tomorrow. the app selection view has been rewritten from scratch and will offer a new design and some new options for customizing is.
![consolation_alpha_5](https://user-images.githubusercontent.com/5193275/32696003-330837ec-c731-11e7-9308-7c5e284b559d.png)

**Comment by sween64** [comment]
That's great news! Thanks for the update.

**Comment by sween64** [comment]
How's alpha 5 coming along?

**Comment by CreatureSurvive** [comment]
@sween64 sorry for the delay, Alpha 5 is now live!

**Comment by sween64** [comment]
Great update thanks! My default background badge colour is red, what would be the settings to get it to look close to alpha 4? Thanks.
