### ISSUE TITLE
Keyboard on type-in number settings shows a comma, can't type a period

### ISSUE THREAD

**Issue by Rougemoot** [CreatureSurvive/consolidation#27]
My phone's main language is French, and I suppose it might be why the number keypad on "Corner Radius", "Vertical Adjustment", etc settings shows a comma (as we use commas for decimal points in french) instead of a period, and the tweak doesn't understand "0,3" as a valid corner radius as opposed to "0.3".

I guess you could either force the keypad to have a period instead of a comma on relevant languages, or make the tweak understand commas as a decimal point.

**Comment by CreatureSurvive** [comment]
Hmm, I was not aware that some languages use commas rather than periods for decimals. Unfortunately IOS doesn't really offer any official way of dealing with this issue, and we can't modify the keyboard either. So I'll fix this by adding support for comma separated decimals in my preference library. That way users who are accustom to using commas can continue to do so. I'll hopefully have this fixed today.

**Comment by Rougemoot** [comment]
Awesome, thank you!

**Comment by CreatureSurvive** [comment]
@Rougemoot so I wasn't able to go through with the fix I had mentioned earlier, I ran into some issues with that approach. However, I have implemented a solution, for languages that use a character other than `.` they will get a regular number keypad with no decimal, then I've added a period to the toolbar that they can use.
![img_0558](https://user-images.githubusercontent.com/5193275/34087700-6d199002-e36a-11e7-928a-41bd12bb4c7f.png)
